"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var util_1 = require("./util");
exports.getXhrBody = util_1.getXhrBody;
exports.getXhrResponseBody = util_1.getXhrResponseBody;
var AjaxClient_1 = require("./AjaxClient");
exports.createHttpCache = AjaxClient_1.createHttpCache;
exports.createHttpContext = AjaxClient_1.createHttpContext;
exports.createHttpRequest = AjaxClient_1.createHttpRequest;
var AjaxClient_2 = require("./AjaxClient");
exports.AjaxClient = AjaxClient_2.AjaxClient;
